Fix error to create 404 page and reformat comments

diff --git a/0x0F-load_balancer/0-custom_http_response_header b/0x0F-load_balancer/0-custom_http_response_header
--- a/0x0F-load_balancer/0-custom_http_response_header
+++ b/0x0F-load_balancer/0-custom_http_response_header
@@ -1,30 +1,88 @@
 #!/usr/bin/env bash
-# Installing and configuring Nginx
-# Custom HTTP header name must be X-Served_By
-# Cutom HTTP header value must be the host name of the server running Nginx
+# This script installs and configures Nginx on an Ubuntu machine
 
-sudo apt-get update && sudo apt-get -y install nginx
+# Uncomment the following line to see the script run in action
+#set -x
 
-# Allow firewall through port 80
+echo -e "Updating and performing some minor checks...\n"
 
+function install() {
+    # Check if the command is available
+    command -v "$1" &> /dev/null
+
+    # Shellcheck disable is used to ignore a shellcheck warning    
+    if [ $? -ne 0 ]; then
+        echo -e "Installing: $1\n"
+        sudo apt-get update -y -qq && \
+            sudo apt-get install -y "$1" -qq
+        echo -e "\n"
+    else
+        echo -e "${1} is already installed.\n"
+    fi
+}
+
+# Install nginx
+install nginx
+
+echo -e "\nSetting up some minor stuff.\n"
+
+# Allowing nginx on the firewall
 sudo ufw allow 'Nginx HTTP'
 
-sudo mkdir -p /var/www/html
+# Give the user ownership of website files for easy editing
+if [ -d "/var/www" ]; then
+    sudo chown -R "$USER":"$USER" /var/www
+    sudo chmod -R 755 /var/www
+else
+    sudo mkdir -p /var/www
+    sudo chown -R "$USER":"$USER" /var/www
+    sudo chmod -R 755 /var/www
+fi
 
-# Allow priviledge to create file in this directory
+# Create directories if not present
+for dir in /var/www/{html,error}; do
+    if ! [ -d "$dir" ]; then
+        mkdir -p "$dir"
+    fi
+done
 
-sudo chmod -R u+x /var/www
+# Create a new index file
+echo "Hello World!" > /var/www/html/index.html
 
-# create main page
-echo 'Hello World!' |sudo tee /var/www/html/index.html
+# Create a new error page
+echo "Ceci n'est pas une page" > /var/www/html/error_404.html
 
-# create page
-echo "Ceci n'est pas une page" |sudo tee /var/html/404.html
+# Backup the default server config file
+sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup
 
-# Configure redirect for a page/redirect_me & adding header for hostname display
-string_for_redirect="server_name_;\n\tadd_header X-Served-By &hostname;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com permanent;"
-sudo sed -i "s/server_name_;/$string_for_redirect/" /etc/nginx/sites_enabled/default
+# Server configuration
+server_config=\
+"server {
+    listen 80 default_server;
+    listen [::]:80 default_server;
+    root /var/www/html;
+    index index.html index.htm index.nginx-debian.html;
+    server_name _;
+    add_header X-Served-By \$hostname;
+    location / {
+        try_files \$uri \$uri/ =404;
+    }
+    if (\$request_filename ~ redirect_me){
+        rewrite ^ https://th3-gr00t.tk/ permanent;
+    }
+    error_page 404 /error_404.html;
+    location = /error_404.html {
+        internal;
+    }
+}"
 
-# 404 page redirection
-string_for_redirect="listen 80 default_server;\n\terror_page \/404.html;\n\tlocation = \/404.html {\nt\troot \/var\/html;\n\tinternal;\n\t}"
-/listen 80 default_server;$string_for_redirect/" /etc/ngnix/sites-enabled/default
+# Shellcheck disable is used to ignore a shellcheck warning
+echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default
+
+# Check if Nginx is running and start or restart accordingly
+if [ "$(pgrep -c nginx)" -le 0 ]; then
+    sudo service nginx start
+else
+    sudo service nginx restart
+fi
+
